# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='ravi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=344),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pinCode',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
